# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "clients.baml": "// BAML client configuration for LiteLLM\n// Supports any model via LiteLLM: OpenAI, Claude, Ollama, etc.\n\nclient<llm> LiteLLM {\n  provider openai-generic\n  options {\n    base_url env.LITELLM_BASE_URL\n    api_key env.LITELLM_API_KEY\n    model env.LITELLM_MODEL\n  }\n}\n\n// Fallback client for local development with Ollama\nclient<llm> Ollama {\n  provider ollama\n  options {\n    base_url \"http://localhost:11434/v1\"\n    model \"llama3.2\"\n  }\n}\n",
    "generators.baml": "// BAML generator configuration\n\ngenerator python {\n  output_type \"python/pydantic\"\n  output_dir \"../goster/baml_client\"\n  version \"0.214.0\"\n}\n",
    "heading.baml": "// Heading classification schema for GOST 7.32-2017 documents\n\nclass HeadingClassification {\n  is_heading bool @description(\"True if text is a section heading\")\n  level int? @description(\"Heading level 1-5, null if not a heading\")\n  is_structural bool @description(\"Structural section: introduction, conclusion, contents, appendix, references\")\n  reasoning string @description(\"Brief explanation of the decision\")\n}\n\nfunction ClassifyHeading(text: string, prev_paragraphs: string[]) -> HeadingClassification {\n  client LiteLLM\n\n  prompt #\"\n    You are an expert in Russian academic document formatting (GOST 7.32-2017).\n\n    Determine if the given text is a section heading.\n\n    Context (previous paragraphs):\n    {{ prev_paragraphs }}\n\n    Text to classify:\n    {{ text }}\n\n    Classification rules:\n    - Level 1: chapters (ГЛАВА N), structural sections (ВВЕДЕНИЕ, ЗАКЛЮЧЕНИЕ, СОДЕРЖАНИЕ)\n    - Level 2: subsections (1.1, 1.2, 2.1)\n    - Level 3+: sub-subsections (1.1.1, 1.1.2, 2.1.1)\n    - Structural sections: ВВЕДЕНИЕ, ЗАКЛЮЧЕНИЕ, СОДЕРЖАНИЕ, РЕФЕРАТ, АННОТАЦИЯ,\n      СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ, СПИСОК ЛИТЕРАТУРЫ, ПРИЛОЖЕНИЕ\n\n    Signs of a heading:\n    - Short text (usually < 100 chars)\n    - Starts with number (1, 1.1, 1.1.1) or \"ГЛАВА\"\n    - Contains structural keywords in uppercase\n    - Does not end with period\n    - Often in uppercase or title case\n\n    Signs of regular paragraph:\n    - Long text with multiple sentences\n    - Ends with period\n    - Contains detailed explanations\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}

def get_baml_files():
    return _file_map